const FILE_PATH = `${__dirname}\\dados.csv`;

const BUFFER_SIZE = 40;

const SIGNAL_TYPES = {
	step: 0,
	upRamp: 1,
	downRamp: 2
}

const FREQUENCIES = [10, 20, 50];

const DEFAULT_SIGNAL = SIGNAL_TYPES.upRamp;
const DEFAULT_OUTPUT = 10;
const DEFAULT_FREQUENCY = FREQUENCIES[0];

module.exports = {
	FILE_PATH: FILE_PATH,
	BUFFER_SIZE: BUFFER_SIZE,
	SIGNAL_TYPES: SIGNAL_TYPES,
	DEFAULT_SIGNAL: DEFAULT_SIGNAL,
	DEFAULT_OUTPUT: DEFAULT_OUTPUT,
	DEFAULT_FREQUENCY: DEFAULT_FREQUENCY,
	FREQUENCIES: FREQUENCIES
};